{{- if eq .Values.secretBackend.type "k8s" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sandcastle.fullname" . }}
  labels:
    {{- include "sandcastle.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "patch"]
{{- end }}
