{{- if or (eq .Values.secretBackend.type "k8s") .Values.sandbox.k8s.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sandcastle.fullname" . }}
  labels:
    {{- include "sandcastle.labels" . | nindent 4 }}
{{- end }}
